---
title: "individual1"
author: "cyber-atlas"
date: "March 28, 2019"
output: html_document
---
```{r}
library("dplyr")
library("tidyr")
library("tidyverse")
library("ggplot2")
library("readxl")
```

```{r}
#load data
defense <- read_excel('cyclonesFootball2018.xlsx', sheet='Defensive')
offense <- read_excel('cyclonesFootball2018.xlsx', sheet='Offensive')
biography <- read_excel('cyclonesFootball2018.xlsx', sheet='Biography')
```

1. 
```{r}
#Cleaning data

defClean <- defense
offClean <- offense
bioClean <- biography



defClean[, "Name"] <- lapply(defClean[, "Name"], as.factor)
defClean[, "Opponent_Opponent"] <- lapply(defClean[, "Opponent_Opponent"], as.factor)
offClean[, "Name"] <- lapply(offClean[, "Name"], as.factor)
offClean[, "Opponent_Opponent"] <- lapply(offClean[, "Opponent_Opponent"], as.factor)
bioClean[, "Name"] <- lapply(bioClean[, "Name"], as.factor)

defClean <- mutate_if(defClean, is.character, as.numeric)
offClean <- mutate_if(offClean, is.character, as.numeric)
bioClean[, "Weight"] <- lapply(bioClean[, "Weight"], as.numeric)

bioClean <- bioClean %>% separate(Height, into=c("Feet", "Inch"), sep="-") %>% mutate(Height = as.numeric(Feet)*12+as.numeric(Inch))
bioClean <- bioClean[, c(1, 2, 9, 5, 6, 7, 8)]

str(defClean)
str(offClean)
str(bioClean)

```
Tidy

1
```{r}
defGather <- gather(defClean,Statistic,Value,-c(1,2))
head(defGather)

```



2
```{r}
ggplot(defGather, aes(x = Opponent_Opponent, y=Value)) + geom_histogram(stat="identity") + 
  facet_wrap(~Statistic) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+ 
  ylab("Count ")+ 
  xlab("Opponent") 
  
```



It looks like all turnover stats are pretty rare




```{r}
perfdf <- defClean %>% 
  filter(Opponent_Opponent == "West Virginia" | Opponent_Opponent == "Kansas State") %>% 
  select(Name, Opponent_Opponent, Tackles_Solo) %>%
  spread(Opponent_Opponent, Tackles_Solo) %>% 
mutate_all(funs(replace(., is.na(.), 0)))
perfdf[is.na(perfdf)] <- 0
perfdf
```
3

```{r}
bioClean<- separate(bioClean, "Hometown", c('City', 'State'), sep = ", ")
states <- bioClean %>% 
  group_by(State) %>% 
  summarise(Num_Players = n())%>%
  arrange(Num_Players, desc(Num_Players))
#states <- states %>%
tail(states,1)

```

Most of the players are from Iowa

```{r}
states
```